### ISSUE TITLE
overlay-offset documentation inconsistency 

### ISSUE THREAD

**Issue by ameliavrieze** [slag-plt/scamper#47]
The current documentation entry for overlay/offset:
(overlay/offset d1 dx dy d2): drawing?

  d1: drawing?
  dx: number?
  dy: number?
  d2: drawing?

The way overlay/offset is currently formatted:
(overlay/offset dx dy d1 d2): drawing?

  dx: number?
  dy: number?
  d1: drawing?
  d2: drawing?

**Comment by psosera** [comment]
Thanks! I made the documentation sync with the API to avoid breaking changes. New docs are now uploaded to the 151 website.
