### ISSUE TITLE
Stepper displaying many extra steps for some list defines

### ISSUE THREAD

**Issue by eric-autry** [slag-plt/scamper#55]
For example, stepping through the following define takes 6 steps:
(define lst (list (pair 0 0) (pair 0 1) (pair 1 0) (pair 1 1)))

Not a major problem, but can get cumbersome/distracting for long lists or lists that contain a lot of strings,

I think it mainly happens when there are pairs or lists inside of the list being defined.

**Comment by psosera** [comment]
Fixed with #34
