### ISSUE TITLE
list-tail bugged

### ISSUE THREAD

**Issue by eric-autry** [slag-plt/scamper#67]
It is giving all elements in [k, len], instead of [len-k, len], i.e., it is dropping the first k elements instead of keeping the last k.

(display (list-tail (list 1 2 3 4 5 6 7 8 9 10) 3))
-> (list 4 5 6 7 8 9 10)

It should produce (list 8 9 10) according to the documentation.

**Comment by psosera** [comment]
Double-checked the Scheme standard. The intended behavior of the function is as implemented:

> `(list-tail list k) procedure`
> It is an error if list has fewer than k elements.
> Returns the sublist of list obtained by omitting the first k
> elements. The list-tail procedure could be defined by
> 
> ~~~racket
> (define list-tail
>   (lambda (x k)
>     (if (zero? k)
>        x
>        (list-tail (cdr x) (- k 1)))))
> ~~~

In other words, `list-tail` is a synonym for `list-drop`. I've fixed the documentation to reflect this fact.
