### ISSUE TITLE
Some midi-notes aren't working

### ISSUE THREAD

**Issue by eric-autry** [slag-plt/scamper#75]
The following only sounds 1 of the 4 notes...

(import music)
(seq (note 56 qn) (note 57 qn) (note 58 qn) (note 59 qn))

**Comment by psosera** [comment]
It appears that other instruments do not exhibit this problem, so _e.g._,

~~~racket
(mod (instrument 12)
  (seq (note 56 qn) (note 57 qn) (note 58 qn) (note 59 qn)))
~~~

Works (`instrument 12` is a marimba). However, given that some notes are missing/not working for one patch, I am unsure whether that means the same holds for other patches.

**Comment by psosera** [comment]
For reference: we use the FluidR3 GM font from `webaudiofont`:

+ https://surikov.github.io/webaudiofontdata/sound/0000_FluidR3_GM_sf2_file.html

All notes across the MIDI range work on the demo page, so the likely culprit is a porting error on my part.

**Comment by psosera** [comment]
Fixed in a previous commit where I removed my hacky port of the patches and added true dynamic loading!
